using System.Collections.Generic;

namespace HiepSiVeVuon.Systems
{
    // He thong dich thuat CHO DU LIEU (item/enemy/quest/warehouse-product ten & mo ta, nap tu
    // data/*.json) - khac voi Loc.cs (dich UI chrome). Tieng Viet trong JSON (items.json,
    // enemies.json, quests.json, warehouse_products.json) VAN LA nguon du lieu goc/mac dinh -
    // cac dictionary duoi day CHI chua ban dich tieng Anh, tra cuu theo Id khi Loc.Current ==
    // Lang.EN (xem ItemDatabase.GetDisplayName/... va WarehouseDatabase.GetDisplayName). Neu
    // thieu 1 Id nao trong nay, code se tu dong fallback ve chuoi tieng Viet trong JSON.
    public static class DataLoc
    {
        // ---- Items (data/items.json) ----
        public static readonly Dictionary<string, string> ItemNamesEn = new()
        {
            ["sword"] = "Steel Sword",
            ["pickaxe"] = "Stone Pickaxe",
            ["hoe"] = "Hoe",
            ["dong_tho"] = "Raw Copper",
            ["sat_tho"] = "Raw Iron",
            ["da_quy"] = "Gemstone",
            ["xuong"] = "Bone",
            ["thao_duoc_rung"] = "Forest Herb",
            ["thao_duoc_dam_lay"] = "Swamp Herb",
            ["quang_nui"] = "Mountain Ore",
            ["ca"] = "Fish",
            ["sen"] = "Lotus Flower",
            ["rong"] = "Pondweed",
            ["can_cau"] = "Fishing Rod",
            ["co_vat"] = "Ancient Relic",
            ["quang_hang"] = "Cave Ore",
            ["shield"] = "Wolf Shield",
            ["ring"] = "Amethyst Ring",
            ["potion"] = "Healing Potion",
            ["coins"] = "Pouch of Gold",
            ["mud_core"] = "Mud Core",
            ["spike_shard"] = "Purple Spike Shard",
            ["wood"] = "Wood",
            ["milk"] = "Cow's Milk",
            ["egg"] = "Chicken Egg",
            ["wool"] = "Sheep's Wool",
            ["cheese"] = "Cheese",
            ["honey"] = "Honey",
            ["beeswax"] = "Beeswax",
            ["fertilizer_basic"] = "Fertilizer",
            ["pesticide"] = "Pesticide",
            ["thucan_giasuc"] = "Livestock Feed",
            ["grape"] = "Grapes",
            ["wine"] = "Wine",
            ["apple"] = "Apple",
            ["pear"] = "Pear",
            ["cherry"] = "Cherry",
            ["peach"] = "Peach",
            ["chestnut"] = "Chestnut",
            ["pumpkin"] = "Pumpkin",
            ["pumpkin_good"] = "Fine Pumpkin",
            ["pumpkin_premium"] = "Premium Pumpkin",
            ["tomato"] = "Tomato",
            ["tomato_good"] = "Fine Tomato",
            ["tomato_premium"] = "Premium Tomato",
            ["wheat"] = "Wheat Bundle",
            ["wheat_good"] = "Fine Wheat",
            ["wheat_premium"] = "Premium Wheat",
            ["carrot"] = "Carrot",
            ["carrot_good"] = "Fine Carrot",
            ["carrot_premium"] = "Premium Carrot",
            ["potato"] = "Potato",
            ["potato_good"] = "Fine Potato",
            ["potato_premium"] = "Premium Potato",
            ["cabbage"] = "Cabbage",
            ["cabbage_good"] = "Fine Cabbage",
            ["cabbage_premium"] = "Premium Cabbage",
            ["pumpkin_seed"] = "Pumpkin Seed",
            ["pumpkin_seed_premium"] = "Premium Pumpkin Seed",
            ["tomato_seed"] = "Tomato Seed",
            ["tomato_seed_premium"] = "Premium Tomato Seed",
            ["wheat_seed"] = "Wheat Seed",
            ["wheat_seed_premium"] = "Premium Wheat Seed",
            ["carrot_seed"] = "Carrot Seed",
            ["carrot_seed_premium"] = "Premium Carrot Seed",
            ["potato_seed"] = "Potato Seed",
            ["potato_seed_premium"] = "Premium Potato Seed",
            ["cabbage_seed"] = "Cabbage Seed",
            ["cabbage_seed_premium"] = "Premium Cabbage Seed",
            ["mut_wheat"] = "Wheat Preserve",
            ["mut_tomato"] = "Tomato Preserve",
            ["mut_carrot"] = "Carrot Preserve",
            ["mut_potato"] = "Potato Preserve",
            ["mut_cabbage"] = "Cabbage Preserve",
            ["mut_pumpkin"] = "Pumpkin Preserve",
            ["ruou_wheat"] = "Wheat Spirits",
            ["ruou_tomato"] = "Tomato Spirits",
            ["ruou_carrot"] = "Carrot Spirits",
            ["ruou_potato"] = "Potato Spirits",
            ["ruou_cabbage"] = "Cabbage Spirits",
            ["ruou_pumpkin"] = "Pumpkin Spirits",
            ["pho_mai"] = "Pressed Cheese",
            ["mayonnaise"] = "Mayonnaise",
            ["vai"] = "Woven Cloth",
            ["mat_ong"] = "Beehive Honey",
            ["sup_rau"] = "Vegetable Soup",
            ["trung_chien"] = "Fried Egg",
            ["banh_bi_ngo"] = "Pumpkin Pie",
            ["salad_ca_chua"] = "Tomato & Cheese Salad",
            ["banh_mi_trung"] = "Egg Bread",
            ["sup_ca"] = "Fish Soup",
            ["cuoc_bac"] = "Silver Hoe",
            ["cuoc_vang"] = "Golden Hoe",
            ["pickaxe_bac"] = "Silver Pickaxe",
            ["pickaxe_vang"] = "Golden Pickaxe",
            ["may_tuoi_tu_dong"] = "Automatic Sprinkler",
            ["da"] = "Stone",
            ["binh_tuoi"] = "Watering Can",
            ["xeng"] = "Shovel",
            ["cao_co"] = "Garden Rake",
        };

        public static readonly Dictionary<string, string> ItemDescriptionsEn = new()
        {
            ["sword"] = "A knight's blade from years past. Sturdy and sharp.",
            ["pickaxe"] = "Used to mine ore underground - equip from your inventory to use.",
            ["hoe"] = "Tills NEW soil out of grass anywhere outside the existing farm grid - equip from your inventory to use.",
            ["dong_tho"] = "Raw copper ore, mined from the mine's first floor.",
            ["sat_tho"] = "Raw iron ore, mined from the mine's second floor.",
            ["da_quy"] = "A rare gem, found only in the mine's deepest level.",
            ["xuong"] = "Bones scavenged from the cemetery ghost - a strange ingredient.",
            ["thao_duoc_rung"] = "Mushrooms and herbs gathered deep in the forest - regrow after a few days.",
            ["thao_duoc_dam_lay"] = "A rare herb that only grows in the damp swamp.",
            ["quang_nui"] = "Mineral ore mined from the mountain cliffs.",
            ["ca"] = "Fish caught from a lake or river.",
            ["sen"] = "A lotus flower picked from the lake.",
            ["rong"] = "Pondweed gathered around the lake.",
            ["can_cau"] = "Used to fish near a lake or river - equip from your inventory to use.",
            ["co_vat"] = "An ancient item found among the ruins.",
            ["quang_hang"] = "Rare ore found deep within the dark caves.",
            ["shield"] = "A wooden shield banded with iron, carved with a wolf's head.",
            ["ring"] = "A mysterious ring that radiates a strange warmth.",
            ["potion"] = "Restores 40 HP when drunk.",
            ["coins"] = "A handful of loose gold coins.",
            ["mud_core"] = "Dropped by mud monsters. Used for crafting.",
            ["spike_shard"] = "A sharp shard from a purple spiked beast. A rare crafting material.",
            ["wood"] = "Chopped from trees in the wild. Used for crafting or sold for gold.",
            ["milk"] = "Fresh milk collected daily from the farm's cows by the cowherd.",
            ["egg"] = "Fresh eggs collected daily from the coop by the chicken keeper.",
            ["wool"] = "Wool sheared from the farm's flock by the herder.",
            ["cheese"] = "Cheese made from fresh cow's milk.",
            ["honey"] = "Honey from the farm's beekeeping garden.",
            ["beeswax"] = "Pure beeswax, used for candles and remedies.",
            ["fertilizer_basic"] = "Spread on planted soil to grow crops faster with better quality.",
            ["pesticide"] = "Spray on pest-infested crops to treat them before quality is lost at harvest.",
            ["thucan_giasuc"] = "Stored feed for your livestock - run out and they truly go hungry.",
            ["grape"] = "A ripe bunch of grapes from the farm's vineyard.",
            ["wine"] = "Wine pressed from homegrown grapes, a countryside specialty.",
            ["apple"] = "A ripe apple from the farm's orchard.",
            ["pear"] = "A ripe pear from the farm's orchard.",
            ["cherry"] = "Ripe red cherries from the farm's orchard.",
            ["peach"] = "A fragrant ripe peach from the farm's orchard.",
            ["chestnut"] = "Chestnuts fallen from the farm's orchard trees.",
            ["pumpkin"] = "A plump, ripe pumpkin - fetches a good price.",
            ["pumpkin_good"] = "A well-tended pumpkin, above-average quality.",
            ["pumpkin_premium"] = "A perfectly-tended pumpkin, top-tier quality.",
            ["tomato"] = "A basket of fresh tomatoes.",
            ["tomato_good"] = "A well-tended tomato, above-average quality.",
            ["tomato_premium"] = "A perfectly-tended tomato, top-tier quality.",
            ["wheat"] = "A golden bundle of wheat.",
            ["wheat_good"] = "Well-tended wheat, above-average quality.",
            ["wheat_premium"] = "Perfectly-tended wheat, top-tier quality.",
            ["carrot"] = "A fresh carrot, crisp and sweet.",
            ["carrot_good"] = "A well-tended carrot, above-average quality.",
            ["carrot_premium"] = "A perfectly-tended carrot, top-tier quality.",
            ["potato"] = "A potato dug fresh from the earth.",
            ["potato_good"] = "A well-tended potato, above-average quality.",
            ["potato_premium"] = "A perfectly-tended potato, top-tier quality.",
            ["cabbage"] = "A lush green cabbage with a tightly-wrapped head.",
            ["cabbage_good"] = "A well-tended cabbage, above-average quality.",
            ["cabbage_premium"] = "A perfectly-tended cabbage, top-tier quality.",
            ["pumpkin_seed"] = "Grows into a pumpkin after 3 days.",
            ["pumpkin_seed_premium"] = "A select seed - grows into a higher-quality pumpkin.",
            ["tomato_seed"] = "Grows into a tomato after 2 days.",
            ["tomato_seed_premium"] = "A select seed - grows into a higher-quality tomato.",
            ["wheat_seed"] = "Grows into wheat after 2 days.",
            ["wheat_seed_premium"] = "A select seed - grows into higher-quality wheat.",
            ["carrot_seed"] = "Grows into a carrot after 2 days.",
            ["carrot_seed_premium"] = "A select seed - grows into a higher-quality carrot.",
            ["potato_seed"] = "Grows into a potato after 3 days.",
            ["potato_seed_premium"] = "A select seed - grows into a higher-quality potato.",
            ["cabbage_seed"] = "Grows into a cabbage after 3 days.",
            ["cabbage_seed_premium"] = "A select seed - grows into a higher-quality cabbage.",
            ["mut_wheat"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["mut_tomato"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["mut_carrot"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["mut_potato"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["mut_cabbage"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["mut_pumpkin"] = "Produce processed at the Dehydrator - worth more than selling it raw.",
            ["ruou_wheat"] = "Brewed at the Press - worth far more than the raw crop.",
            ["ruou_tomato"] = "Brewed at the Press - worth far more than the raw crop.",
            ["ruou_carrot"] = "Brewed at the Press - worth far more than the raw crop.",
            ["ruou_potato"] = "Brewed at the Press - worth far more than the raw crop.",
            ["ruou_cabbage"] = "Brewed at the Press - worth far more than the raw crop.",
            ["ruou_pumpkin"] = "Brewed at the Press - worth far more than the raw crop.",
            ["pho_mai"] = "Pressed from cow's milk - worth more than the raw milk.",
            ["mayonnaise"] = "Made from chicken eggs - worth more than the raw eggs.",
            ["vai"] = "Woven from sheep's wool - worth more than the raw wool.",
            ["mat_ong"] = "Harvested straight from the hive - needs no daily care.",
            ["sup_rau"] = "Cooked from carrot and cabbage - restores stamina.",
            ["trung_chien"] = "Cooked from 2 chicken eggs - restores stamina.",
            ["banh_bi_ngo"] = "Baked from pumpkin and milk - restores a large amount of stamina.",
            ["salad_ca_chua"] = "Made from tomato and cheese - restores a large amount of stamina.",
            ["banh_mi_trung"] = "Baked from wheat and chicken egg - restores stamina.",
            ["sup_ca"] = "Cooked from fish and carrot - restores stamina.",
            ["cuoc_bac"] = "An upgraded hoe - tills/waters/harvests a full 3x3 area around your target instead of one tile at a time.",
            ["cuoc_vang"] = "The finest hoe upgrade - tills/waters/harvests a full 5x5 area around your target.",
            ["pickaxe_bac"] = "An upgraded pickaxe - mines ore with greater power.",
            ["pickaxe_vang"] = "The finest pickaxe upgrade - mines ore with tremendous power.",
            ["may_tuoi_tu_dong"] = "Equip it and press Space near a soil tile to place it - automatically waters the surrounding tiles EVERY DAY.",
            ["da"] = "A basic building material - used to construct houses and pens through the Build Menu.",
            ["binh_tuoi"] = "A dedicated watering tool - waters more evenly than a plain hoe, giving crops a small boost to health and quality.",
            ["xeng"] = "A dedicated tilling tool - clears a 2x2 patch of new soil at once, faster than a regular Hoe.",
            ["cao_co"] = "Scrapes pests off crops by hand - no need to spend Pesticide.",
        };

        // ---- Enemies (data/enemies.json) ----
        public static readonly Dictionary<string, string> EnemyNamesEn = new()
        {
            ["mud_monster"] = "Mud Monster",
            ["spiky_monster"] = "Purple Spiky Beast",
            ["forest_wolf"] = "Forest Wolf",
            ["mountain_troll"] = "Mountain Troll",
            ["lake_serpent"] = "Lake Serpent",
            ["swamp_lurker"] = "Swamp Lurker",
            ["ruins_wraith"] = "Ruins Wraith",
            ["cemetery_ghost"] = "Cemetery Ghost",
            ["cave_bat"] = "Cave Bat",
        };

        // ---- Quests (data/quests.json) ----
        public static readonly Dictionary<string, string> QuestTitlesEn = new()
        {
            ["q_first_harvest"] = "First Harvest",
            ["q_clear_mud"] = "Clearing the Woods",
            ["q_spiky_hunt"] = "The Purple Threat",
        };

        public static readonly Dictionary<string, string> QuestDescriptionsEn = new()
        {
            ["q_first_harvest"] = "Harvest your first 3 pumpkins from the field.",
            ["q_clear_mud"] = "Defeat 3 Mud Monsters that are ravaging the crops.",
            ["q_spiky_hunt"] = "Hunt down a Purple Spiky Beast deep in the caves.",
        };

        // ---- Warehouse products (data/warehouse_products.json) ----
        public static readonly Dictionary<string, string> WarehouseProductNamesEn = new()
        {
            ["sack"] = "Sack",
            ["crate"] = "Wooden Crate",
            ["barrel"] = "Wooden Barrel",
            ["hay"] = "Hay Bale",
            ["pumpkin_stock"] = "Harvested Pumpkins",
            ["wheat_stock"] = "Harvested Wheat",
            ["egg"] = "Chicken Eggs",
        };
    }
}
